### PR TITLE
Minor spelling and grammar fixes

### PR DESCRIPTION
**Pull request by zbraiterman**

### CODE REVIEW

**Comment by TomCJones** [comment]
i updated with new link - i think i have all of your edits - please pull and check - thanks

**Comment by zbraiterman** [comment]
Thank you, @TomCJones.  None of my suggested updates seem to have been applied in this GitHub repository itself.

**Comment by TomCJones** [comment]
Right you are - I also made a change requested by Noreen.  Thanks for your sharp eye on this.

**Comment by zbraiterman** [comment]
> Right you are - I also made a change requested by Noreen. Thanks for your sharp eye on this.

Glad to hear that.  Noreen is brilliant!

**Comment by TomCJones** [comment]
merged with other input

**Pull request closed without merging**
